services:
  postgres:
    container_name: ziplink-postgres-container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=ziplink
    volumes:
      - ziplink-postgres-data:/var/lib/postgresql/data

  redis:
    container_name: ziplink-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ziplink-redis-data:/data

  backend:
    container_name: ziplink-backend
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend

    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://prisma:mysecretpassword@postgres:5432/ziplink
      - CLIENT_URL=http://localhost:5173
      - UPSTASH_REDIS_URL=redis://ziplink-redis:6379
      - BASE_URL=http://localhost:3000/api/v1/zipLink
      - JWT_SECRET=somehashstring
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    restart: unless-stopped

  worker:
    container_name: ziplink-worker
    build:
      context: ../
      dockerfile: docker/Dockerfile.worker

    environment:
      - DATABASE_URL=postgresql://prisma:mysecretpassword@postgres:5432/ziplink
      - UPSTASH_REDIS_URL=redis://ziplink-redis:6379
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    container_name: ziplink-frontend
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    volumes:
      - ziplink-frontend_build:/usr/share/nginx/html

volumes:
  ziplink-frontend_build:
  ziplink-postgres-data:
  ziplink-redis-data:
